data:
  image: debian:jessie
  volumes:
    - /data
  command: /bin/bash -c 'touch /data/.permission && chown -R www-data:www-data /data'
registry:
  image: registry:2
  volumes_from:
    - data
  volumes:
    - config.yml:/go/src/github.com/docker/distribution/cmd/registry/config.yml:ro
  ports:
    - "5000:5000"
  user: www-data
  restart: always
