data:
  image: debian:jessie
  volumes:
    - /data
  command: /bin/bash -c 'touch /data/.permission && chown -R www-data:www-data /data'
registry:
  build: registry/
  volumes_from:
    - data
  ports:
    - "5000:5000"
  restart: always
